[autopeer]
user = "_dn42-autopeer" # privileges are automatically dropped to this user/group
group = "_dn42-autopeer"
registry = "/var/db/dn42-autopeer/registry"
db_dir = "/var/db/dn42-autopeer/database"
wg_base_port = 2100  # all peers will be assigned a port starting from this value
ADMIN_ASN = 424242XXXX # allows the admin to manage peers
wg_rdomain = 42 # the routing domain used by wireguard
router_ip4 = "172.2X.X.X" # the DN42 IPv4 address of the router
router_ip6 = "fd::X:X:X" # the DN42 IPv6 address of the router

[uvicorn]
# any options for uvicorn can be set here
host = "127.0.0.1"
port = 8000
