m_001 = [
    """
CREATE TABLE IF NOT EXISTS peerinfo (
    ASN INT PRIMARY KEY NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PEER_IP TEXT NOT NULL UNIQUE,
    PEER_PORT INT NOT NULL,
    PEER_PUBKEY TEXT NOT NULL UNIQUE,
    PEER_PSK TEXT NOT NULL UNIQUE,
    LL_IP4 TEXT NOT NULL UNIQUE,
    LL_IP6 TEXT NOT NULL UNIQUE,
    DN42_IP4 TEXT NOT NULL UNIQUE,
    DN42_IP6 TEXT NOT NULL UNIQUE
    );
""",
    "CREATE INDEX IF NOT EXISTS idx_ASN ON peerinfo (ASN);",
    "CREATE INDEX IF NOT EXISTS idx_DESCRIPTION ON peerinfo (DESCRIPTION);",
    "CREATE INDEX IF NOT EXISTS idx_PEER_IP ON peerinfo (PEER_IP);",
    "CREATE INDEX IF NOT EXISTS idx_PEER_PORT ON peerinfo (PEER_PORT);",
    "CREATE INDEX IF NOT EXISTS idx_PEER_PUBKEY ON peerinfo (PEER_PUBKEY);",
    "CREATE INDEX IF NOT EXISTS idx_PEER_PSK ON peerinfo (PEER_PSK);",
    "CREATE INDEX IF NOT EXISTS idx_LL_IP4 ON peerinfo (LL_IP4);",
    "CREATE INDEX IF NOT EXISTS idx_LL_IP6 ON peerinfo (LL_IP6);",
    "CREATE INDEX IF NOT EXISTS idx_DN42_IP4 ON peerinfo (DN42_IP4);",
    "CREATE INDEX IF NOT EXISTS idx_DN42_IP6 ON peerinfo (DN42_IP6);",
]

migrations = [
    m_001,
]
