"""initial

Revision ID: 2ef903fcfe98
Revises: 
Create Date: 2024-12-13 22:22:37.662211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ef903fcfe98"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peerinfo",
        sa.Column("ASN", sa.Integer(), nullable=False),
        sa.Column("DESCRIPTION", sa.String(length=44), nullable=False),
        sa.Column("WG_ID", sa.Integer(), nullable=False),
        sa.Column("WG_PRIVKEY", sa.String(length=44), nullable=False),
        sa.Column("WG_PORT", sa.Integer(), nullable=False),
        sa.Column("PEER_IP", sa.String(), nullable=True),
        sa.Column("PEER_PORT", sa.Integer(), nullable=True),
        sa.Column("PEER_PUBKEY", sa.String(length=44), nullable=False),
        sa.Column("PEER_PSK", sa.String(length=44), nullable=True),
        sa.Column("PEER_LL_IP4", sa.String(), nullable=True),
        sa.Column("PEER_LL_IP6", sa.String(), nullable=True),
        sa.Column("DN42_IP4", sa.String(), nullable=True),
        sa.Column("DN42_IP6", sa.String(), nullable=True),
        sa.Column("OUR_LL_IP4", sa.String(), nullable=False),
        sa.Column("OUR_LL_IP6", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("ASN"),
        sa.UniqueConstraint("DN42_IP4"),
        sa.UniqueConstraint("DN42_IP6"),
        sa.UniqueConstraint("OUR_LL_IP4"),
        sa.UniqueConstraint("OUR_LL_IP6"),
        sa.UniqueConstraint("PEER_IP"),
        sa.UniqueConstraint("PEER_LL_IP4"),
        sa.UniqueConstraint("PEER_LL_IP6"),
        sa.UniqueConstraint("PEER_PSK"),
        sa.UniqueConstraint("PEER_PUBKEY"),
        sa.UniqueConstraint("WG_ID"),
        sa.UniqueConstraint("WG_PORT"),
        sa.UniqueConstraint("WG_PRIVKEY"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("peerinfo")
    # ### end Alembic commands ###
