"""add wireguard privkey column

Revision ID: 45cee54fa6c2
Revises: 659ce502bb21
Create Date: 2024-12-12 02:45:11.347992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cee54fa6c2'
down_revision: Union[str, None] = '659ce502bb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peerinfo', sa.Column('WG_PRIVKEY', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'peerinfo', ['WG_PRIVKEY'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peerinfo', 'WG_PRIVKEY')
    # ### end Alembic commands ###
