"""new attributes

Revision ID: 64ae77150556
Revises: 2ef903fcfe98
Create Date: 2024-12-13 22:47:12.061695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64ae77150556"
down_revision: Union[str, None] = "2ef903fcfe98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("peerinfo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("USE_LL_IP4", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("USE_LL_IP6", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("MP_BGP", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("EXTENDED_NEXT_HOP", sa.Boolean(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("peerinfo", schema=None) as batch_op:
        batch_op.drop_column("EXTENDED_NEXT_HOP")
        batch_op.drop_column("MP_BGP")
        batch_op.drop_column("USE_LL_IP6")
        batch_op.drop_column("USE_LL_IP4")

    # ### end Alembic commands ###
