"""add wireguard privkey column

Revision ID: c1474a07cb86
Revises: 659ce502bb21
Create Date: 2024-12-12 02:57:59.365191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1474a07cb86'
down_revision: Union[str, None] = '659ce502bb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peerinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('WG_PRIVKEY', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['WG_PRIVKEY'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peerinfo', schema=None) as batch_op:
        batch_op.drop_column('WG_PRIVKEY')

    # ### end Alembic commands ###
