"""initial

Revision ID: 659ce502bb21
Revises: 
Create Date: 2024-12-11 00:13:49.704775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659ce502bb21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peerinfo',
    sa.Column('ASN', sa.Integer(), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=30), nullable=False),
    sa.Column('PEER_IP', sa.String(), nullable=False),
    sa.Column('PEER_PORT', sa.Integer(), nullable=False),
    sa.Column('PEER_PUBKEY', sa.String(length=30), nullable=False),
    sa.Column('PEER_PSK', sa.String(length=30), nullable=False),
    sa.Column('LL_IP4', sa.String(), nullable=False),
    sa.Column('LL_IP6', sa.String(), nullable=False),
    sa.Column('DN42_IP4', sa.String(), nullable=False),
    sa.Column('DN42_IP6', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ASN'),
    sa.UniqueConstraint('DN42_IP4'),
    sa.UniqueConstraint('DN42_IP6'),
    sa.UniqueConstraint('LL_IP4'),
    sa.UniqueConstraint('LL_IP6'),
    sa.UniqueConstraint('PEER_IP'),
    sa.UniqueConstraint('PEER_PSK'),
    sa.UniqueConstraint('PEER_PUBKEY')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peerinfo')
    # ### end Alembic commands ###
